# Generated by Django 4.2.4 on 2023-08-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="username",
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_naissance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="Téléphone"
            ),
        ),
    ]
