# Generated by Django 4.2.4 on 2023-08-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_remove_patient_username_alter_patient_date_naissance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
