# Generated by Django 4.2.4 on 2023-08-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_client_commande_lignecommande_commande_articles_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="Customer",
        ),
    ]
